podSecurityPolicy:
  create: true

falco:
  image:
    registry: docker.io
    repository: giantswarm/falco
  priorityClassName: giantswarm-critical
  driver:
    kind: ebpf
  # ebpf:
  #   enabled: true
  falco:
    grpc:
      enabled: true
    grpc_output:
      enabled: true
  serviceAccount:
    # We set the service account name only so that we can use it for attaching a PSP.
    name: "falco"

falco-exporter:
  image:
    registry: docker.io
    repository: giantswarm/falco-exporter
  podSecurityPolicy:
    create: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

falcosidekick:
  image:
    registry: docker.io
    repository: giantswarm/falcosidekick
